permissions:
  id-token: write # required to use OIDC authentication
  contents: read # required to checkout the code from the repo

name: Build and Push to ECR
# Only run one deploy at a time for a given branch
concurrency: ci-${{ github.ref }}

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs: 
  build_and_push:
    name: Build and Push
    runs-on: "non-prod-amd64"
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::194182751502:role/ci-selenium
          aws-region: eu-west-1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/engineering/selenium:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
