name: Hyperexecute-iPhone-Two
on:
  schedule:
#    - cron: '0 0 * * 2'
  workflow_dispatch:
  
jobs:
  HyperExecute:
    runs-on: non-prod-amd64-lite
    timeout-minutes: 300

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Starting CLI testing
        shell: bash
        run: |
           curl https://downloads.lambdatest.com/hyperexecute/linux/hyperexecute -o hyperexecute
          chmod +x hyperexecute
          ./hyperexecute --user qachamp --key tWQVarNtZUjpqm8Aly0otJ9mVeHw0rjD9BXRV6ijInnfzjzCn3 --config yaml_files/iphone/iphone_two.yaml -v
          echo "Test completion"
