name: Hyperexecute-iPhone-One
on:
  schedule:
   - cron: '0 22 * * 3'
  workflow_dispatch:
  
jobs:
  HyperExecute:
    runs-on: non-prod-amd64-lite
    timeout-minutes: 300

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Starting CLI testing
        shell: bash
        run: |
          curl https://downloads.lambdatest.com/hyperexecute/linux/hyperexecute -o hyperexecute
          chmod +x hyperexecute
          # export LT_USERNAME="qachamp"
          # export LT_ACCESS_KEY="tWQVarNtZUjpqm8Aly0otJ9mVeHw0rjD9BXRV6ijInnfzjzCn3"
          # echo $LT_USERNAME 
          # echo $LT_ACCESS_KEY
          ./hyperexecute --user qachamp --key tWQVarNtZUjpqm8Aly0otJ9mVeHw0rjD9BXRV6ijInnfzjzCn3 --config yaml_files/iphone/iphone_one.yaml -v
          echo "Test completion"

