on:
  workflow_call:
    inputs:
      web_domain:
        type: string
        description: "The domain used for web access"
        default: "web.tails-nonprod.com"
        required: false
      timeout:
        type: number
        description: "The workflow timeout"
        default: 15
        required: false

jobs:
  selenium_tests:
    name: Run Selenium tests
    runs-on: non-prod-amd64
    timeout-minutes: ${{ inputs.timeout }}
    defaults:
      run:
        working-directory: /usr/app
    strategy:
      fail-fast: false
      matrix:
        test:
          - 1_pipeline_uk_stripe
          - 2_pipeline_uk_man_address_stripe
          - 3_pipeline_fr_stripe
          - 4_pipeline_de_stripe
          - 5_pipeline_de_gocardless
          - 7_pipeline_dss_data
          - 8_pipeline_uk_dashboard
    services:
      selenium:
        image: 426105708615.dkr.ecr.eu-west-1.amazonaws.com/seleniarm/standalone-chromium:4.10
        ports:
          - 4444:4444
        options: >-
          --health-cmd "curl localhost:4444"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    container: 194182751502.dkr.ecr.eu-west-1.amazonaws.com/engineering/selenium:latest
    steps:
      - run: |
          echo "Running against $TEST_URL"
          behave features/pipeline_features/${{ matrix.test }}.feature
        env:
          SELENIUM_REMOTE_URL: http://selenium:4444
          TEST_URL: https://${{ inputs.web_domain }}
